# 测试调用web层
POST https://{{host}}/api-base/users/login
Content-Type: application/json

{
  "loginName": "fanyao",
  "password": "123"
}

###

# 测试调用web层参数校验异常
POST https://{{host}}/api-base/users/login
Content-Type: application/json

{
}

###

# 测试调用异常情况
GET https://{{host}}/api-base/users/error

###



###
