spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
  upload-path: 'http://192.168.99.54:7000/group1/upload'
  auth-url: '/file/token/auth'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    dubbo:
      enable: true
      dubbo-shutdown.enabled: true
      dubbo-configs.enabled: true
      dubbo-services.enabled: true
      dubbo-references.enabled: true
      dubbo-properties.enabled: true
  health:
    dubbo:
      status:
        defaults: memory,load
        extras: registry,load,threadpool

