spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: web-base
          uri: lb://dubbo-web-base
          predicates:
              - Path=/api-base/**
          filters:
            - StripPrefix=1
        - id: web-auth
          uri: lb://dubbo-web-auth
          predicates:
            - Path=/api-auth/**
          filters:
            - StripPrefix=1

