spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: web
          uri: lb://dubbo-web-user
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1

