dubbo:
  registry:
    address: spring-cloud://localhost
  consumer:
    timeout: 10000
    retries: 0
  cloud:
    subscribed-services: dubbo-server-base

#   redis start #
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
#   redis end  #

# jwt start #
jwt:
  # request header name
  header: 'Authorization'
  # token attributes
  userId: 'userId'
  userName: 'userName'
  roles: 'roles'

# jwt end #

