spring:
  datasource:
    druid:
      #连接信息
      url: jdbc:mysql:///test?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
